apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yt-viewer-tracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/wasim0028/yt-viewer-tracker.git
    targetRevision: main
    path: deployment/k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: yt-viewer-tracker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
